services:
    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        ports:
            - "9100:9100"
        volumes:
            - "/:/host:ro,rslave"
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        command:
            - "--path.rootfs=/host"
            - "--collector.processes"
            - "--collector.textfile.directory=/host/usr/lib/node-exporter/textfile"
