groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        annotations:
          title: 'Host is down'
        labels:
          severity: 'Critical'

      - alert: HostMemoryUsage
        expr: (((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100) > 80
        for: 1m
        annotations:
          title: 'Memory usage > 80%'
        labels:
          severity: 'Warning'

      - alert: HostDiskSpaceUsage
        expr: ((sum(max by (device) (node_filesystem_size_bytes{fstype!=""} - node_filesystem_avail_bytes{fstype!=""})) / sum(max by (device) (node_filesystem_size_bytes{fstype!=""}))) * 100) > 80
        for: 1m
        annotations:
          title: 'Disk usage > 80%'
        labels:
          severity: 'Warning' 

      - alert: SSHFailure
        expr: ssh_failure == 1
        for: 1m
        annotations:
          title: 'SSH Failed: {{ $labels.reason }}'
        labels:
          severity: 'Critical'

      - alert: ManyProcesses
        expr: sum(node_processes_state) > 500
        for: 1m
        annotations:
          title: 'Processes count > 500'
        labels:
          severity: 'Critical'


