route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'gmail'

receivers:
  - name: 'gmail'
    email_configs:
      - to: wjayteo@gmail.com
        from: wjayteo@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: wjayteo@gmail.com
        auth_identity: wjayteo@gmail.com
        auth_password: eyrpvmqqjqxemrcd
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
