route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'gmail'

receivers:
  - name: 'gmail'
    email_configs:
      - to: wjayteo@gmail.com
        from: alerts.prometheus.wjayteo@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: alerts.prometheus.wjayteo@gmail.com
        auth_identity: alerts.prometheus.wjayteo@gmail.com
        auth_password: ptqndtvvuseshsln
        send_resolved: true
        headers:
          subject: '[{{ if eq .Status "firing" }}{{ .CommonLabels.severity }}{{ else }}RESOLVED{{ end }}] {{ .CommonAnnotations.title }}'
        html: '{{ if eq .Status "firing" }}{{ .CommonAnnotations.summary }}{{ else }}Issue has been resolved.{{ end }}<br/><br/>Instance: {{ .CommonLabels.instance }}<br/>Job: {{ .CommonLabels.job }}<br/>Alert name: {{ .CommonLabels.alertname }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
