route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'gmail'

receivers:
  - name: 'gmail'
    email_configs:
      - to: wjayteo@gmail.com
        from: alert.prometheus.wjayteo@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: alert.prometheus.wjayteo@gmail.com
        auth_identity: alert.prometheus.wjayteo@gmail.com
        auth_password: ptqndtvvuseshsln
        send_resolved: true
        headers:
          subject: '{{ template "email.subject.text" }}'
        html: '{{ template "email.message.html" }}'
        
templates:
  - '/etc/alertmanager/templates/email.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
