groups:
  - name: AllInstances
    rules:
      - alert: UnidentifiedUsers
        expr: node_unid_users > 0
        for: 1m
        annotations:
          title: 'Unidentified users logged into {{ $labels.instance }}'
        labels:
          severity: 'Critical'
          
      - alert: VulnerablePortOpened
        expr: node_vuln_ports > 0
        for: 1m
        annotations:
          title: 'A vulnerable port is opened on {{ $labels.instance }}'
        labels:
          severity: 'Critical'
          
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        annotations:
          title: 'Host is down'
        labels:
          severity: 'Critical'

      - alert: HostMemoryUsage
        expr: (((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100) > 80
        for: 1m
        annotations:
          title: 'Memory usage > 80% for host {{ $labels.instance }}'
        labels:
          severity: 'Warning'

      - alert: HostDiskSpaceUsage
        expr: ((sum(max by (device) (node_filesystem_size_bytes{fstype!=""} - node_filesystem_avail_bytes{fstype!=""})) / sum(max by (device) (node_filesystem_size_bytes{fstype!=""}))) * 100) > 80
        for: 1m
        annotations:
          title: 'Disk usage > 80% for host {{ $labels.instance }}'
        labels:
          severity: 'Warning' 

      - alert: SSHFailure
        expr: ssh_failure == 1
        for: 1m
        annotations:
          title: 'SSH Failed: {{ $labels.reason }} for host {{ $labels.instance }}'
        labels:
          severity: 'Critical'


