groups:
  - name: AllInstances
    rules:
      - alert: UnidentifiedUsers
        expr: node_unid_users > 0
        for: 1m
        annotations:
          title: 'Unidentified user(s) - {{ $labels.instance }}'
          summary: '{{ $value }} unidentifed user login(s) detected.'
        labels:
          severity: 'Critical'
          
      - alert: VulnerablePortOpened
        expr: node_vuln_ports > 0
        for: 1m
        annotations:
          title: 'Vulerable port(s) - {{ $labels.instance }}'
          summary: '{{ $value }} vulnerable port(s) are in use.'
        labels:
          severity: 'Critical'
          
      - alert: check_all_discs_warning
        expr: (node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) * 100 < 20
        for: 5m
        annotations:
          title: 'Disk space - {{ $labels.instance }}'
          summary: 'Host has {{ $value }}% disk space available.'
        labels:
          severity: 'Warning'
          
      - alert: check_all_discs_critical
        expr: (node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) * 100 < 10
        for: 5m
        annotations:
          title: 'Disk space - {{ $labels.instance }}'
          summary: 'Host has {{ $value }}% disk space available.'
        labels:
          severity: 'Critical'
          
      - alert: check_load1_warning
        expr: node_load1 > 5.0
        for: 5m
        annotations:
          title: 'CPU load (1m) - {{ $labels.instance }}'
          summary: 'Average CPU load (1m) for host is {{ $value }}.'
        labels:
          severity: 'Warning'
          
      - alert: check_load1_critical
        expr: node_load1 > 10.0
        for: 5m
        annotations:
          title: 'CPU load (1m) - {{ $labels.instance }}'
          summary: 'Average CPU load (1m) for host is {{ $value }}.'
        labels:
          severity: 'Critical'
          
      - alert: check_load5_warning
        expr: node_load5 > 4.0
        for: 5m
        annotations:
          title: 'CPU load (5m) - {{ $labels.instance }}'
          summary: 'Average CPU load (5m) for host is {{ $value }}.'
        labels:
          severity: 'Warning'
          
      - alert: check_load5_critical
        expr: node_load5 > 6.0
        for: 5m
        annotations:
          title: 'CPU load (5m) - {{ $labels.instance }}'
          summary: 'Average CPU load (5m) for host is {{ $value }}.'
        labels:
          severity: 'Critical'
          
      - alert: check_load15_warning
        expr: node_load15 > 3.0
        for: 5m
        annotations:
          title: 'CPU load (15m) - {{ $labels.instance }}'
          summary: 'Average CPU load (15m) for host is {{ $value }}.'
        labels:
          severity: 'Warning'
          
      - alert: check_load15_critical
        expr: node_load15 > 4.0
        for: 5m
        annotations:
          title: 'CPU load (15m) - {{ $labels.instance }}'
          summary: 'Average CPU load (15m) for host is {{ $value }}.'
        labels:
          severity: 'Critical'
          
      - alert: check_processes_warning
        expr: sum by (instance) (node_processes_state) > 310
        for: 5m
        annotations:
          title: 'Processes - {{ $labels.instance }}'
          summary: 'Host has {{ $value }} processes.'
        labels:
          severity: 'Warning'
          
      - alert: check_processes_critical
        expr: sum by (instance) (node_processes_state) > 400
        for: 5m
        annotations:
          title: 'Processes - {{ $labels.instance }}'
          summary: 'Host has {{ $value }} processes.'
        labels:
          severity: 'Critical'
          
      - alert: check_users_warning
        expr: node_current_users > 20
        for: 5m
        annotations:
          title: 'Users - {{ $labels.instance }}'
          summary: 'Host currently has {{ $value }} users logged in.'
        labels:
          severity: 'Warning'
          
      - alert: check_users_warning
        expr: node_current_users > 50
        for: 5m
        annotations:
          title: 'Users - {{ $labels.instance }}'
          summary: 'Host currently has {{ $value }} users logged in.'
        labels:
          severity: 'Critical'

